### ISSUE TITLE
laravel 8 update

### ISSUE THREAD

**Issue by siarheipashkevich** [czechbox/laravelplans#8]
Do you think you will update this package to support laravel 8? Thanks

**Comment by siarheipashkevich** [comment]
@czechbox could you please update your package for supporting laravel 8?

**Comment by siarheipashkevich** [comment]
@czechbox are you support this package?

**Comment by siarheipashkevich** [comment]
@czechbox please merge PR above.

**Comment by czechbox** [comment]
Hey, sorry been working on another branch to add cashier integration, but this looks fine, have merged
